repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff lint
      entry: ruff check strava_auth/
      language: system
      always_run: true
      pass_filenames: false
    - id: mypy
      name: mypy
      entry: mypy strava_auth/ --strict-equality
      language: system
      always_run: true
      pass_filenames: false
