name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python --version
        python -m pip install -r requirements.txt --upgrade pip
        pip install pytest pytest-cov

    - name: Run pytest
      run: pytest --cov=strava_auth test/
